### PR TITLE
Added cat2.txt file

### PR DESCRIPTION
**Pull request by sauliuskucevicius**
- Added cat2.txt file with cat high 5

### CODE REVIEW

**Comment by tuhelahmed98** [comment]
cat high cat bye

**Comment by Rigshan** [comment]
seen the cat2.txt file - good work

**Review by squishypandakay — CHANGES_REQUESTED** [review]
Look for Santa cat please :)

**Comment by sauliuskucevicius** [comment]
> Look for Santa cat please :)

On it now!

**Review by squishypandakay — APPROVED** [review]
Amazing Santa Paws, love it

**Pull request merged**
